import { Product } from '../types';

export const testProducts: Product[] = [
  {
    id: 'hermes-parfum-1',
    name: 'Hermès Parfum',
    brand: 'Hermès',
    description: 'Ein exklusives Hermès Parfum mit edlen Duftnoten',
    shortDescription: 'Exklusives Hermès Parfum',
    price: 89.99,
    currency: 'EUR',
    images: [require('../../assets/hermes_parfum.png')],
    category: 'parfum',
    type: 'original',
    gender: 'unisex',
    notes: [
      { id: '1', name: 'Rose', type: 'heart', category: 'blumig' },
      { id: '2', name: 'Sandelholz', type: 'base', category: 'holz' },
      { id: '3', name: 'Bergamotte', type: 'top', category: 'zitrus' },
    ],
    concentration: 'Parfum',
    volume: '50ml',
    availability: 8,
    isLimited: false,
    isExclusive: true,
    isNew: true,
    isOnSale: false,
    rating: 4.9,
    reviewCount: 67,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'hermes-parfum-gelb-2',
    name: 'Hermès Parfum Gelb',
    brand: 'Hermès',
    description: 'Ein elegantes Hermès Parfum in gelber Ausführung',
    shortDescription: 'Elegantes Hermès Parfum in Gelb',
    price: 95.99,
    currency: 'EUR',
    images: [require('../../assets/hermes_parum_gelb.png')],
    category: 'parfum',
    type: 'original',
    gender: 'unisex',
    notes: [
      { id: '4', name: 'Jasmin', type: 'heart', category: 'blumig' },
      { id: '5', name: 'Amber', type: 'base', category: 'orientalisch' },
      { id: '6', name: 'Limette', type: 'top', category: 'zitrus' },
    ],
    concentration: 'Parfum',
    volume: '50ml',
    availability: 5,
    isLimited: true,
    isExclusive: true,
    isNew: false,
    isOnSale: false,
    rating: 4.8,
    reviewCount: 42,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: 'louis-vuitton-red-3',
    name: 'Louis Vuitton Red',
    brand: 'Louis Vuitton',
    description: 'Ein leidenschaftlicher Duft in Rot von Louis Vuitton',
    shortDescription: 'Leidenschaftlicher Louis Vuitton Duft',
    price: 120.99,
    currency: 'EUR',
    images: [require('../../assets/loui_vuitton_red.png')],
    category: 'eau-de-parfum',
    type: 'original',
    gender: 'feminine',
    notes: [
      { id: '7', name: 'Rose', type: 'heart', category: 'blumig' },
      { id: '8', name: 'Vanille', type: 'base', category: 'gourmand' },
      { id: '9', name: 'Pfeffer', type: 'top', category: 'würzig' },
    ],
    concentration: 'Eau de Parfum',
    volume: '100ml',
    availability: 12,
    isLimited: false,
    isExclusive: true,
    isNew: true,
    isOnSale: false,
    rating: 4.7,
    reviewCount: 89,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'louis-vuitton-blue-4',
    name: 'Louis Vuitton Blue',
    brand: 'Louis Vuitton',
    description: 'Ein frischer, maritimer Duft in Blau von Louis Vuitton',
    shortDescription: 'Frischer, maritimer Louis Vuitton Duft',
    price: 115.99,
    currency: 'EUR',
    images: [require('../../assets/louis_vuitton_blue.png')],
    category: 'eau-de-parfum',
    type: 'original',
    gender: 'masculine',
    notes: [
      { id: '10', name: 'Meersalz', type: 'top', category: 'maritim' },
      { id: '11', name: 'Holz', type: 'base', category: 'holz' },
      { id: '12', name: 'Bergamotte', type: 'top', category: 'zitrus' },
    ],
    concentration: 'Eau de Parfum',
    volume: '100ml',
    availability: 15,
    isLimited: false,
    isExclusive: true,
    isNew: false,
    isOnSale: true,
    originalPrice: 130.99,
    rating: 4.6,
    reviewCount: 156,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: 'prada-ocean-5',
    name: 'Prada Ocean',
    brand: 'Prada',
    description: 'Ein erfrischender Ozean-Duft von Prada',
    shortDescription: 'Erfrischender Prada Ozean-Duft',
    price: 78.99,
    currency: 'EUR',
    images: [require('../../assets/prada_ocean.png')],
    category: 'eau-de-toilette',
    type: 'original',
    gender: 'unisex',
    notes: [
      { id: '13', name: 'Meersalz', type: 'top', category: 'maritim' },
      { id: '14', name: 'Algen', type: 'heart', category: 'maritim' },
      { id: '15', name: 'Amber', type: 'base', category: 'orientalisch' },
    ],
    concentration: 'Eau de Toilette',
    volume: '75ml',
    availability: 20,
    isLimited: false,
    isExclusive: false,
    isNew: true,
    isOnSale: false,
    rating: 4.5,
    reviewCount: 234,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: 'ralph-lauren-rot-6',
    name: 'Ralph Lauren Rot',
    brand: 'Ralph Lauren',
    description: 'Ein eleganter, roter Duft von Ralph Lauren',
    shortDescription: 'Eleganter Ralph Lauren Duft in Rot',
    price: 65.99,
    currency: 'EUR',
    images: [require('../../assets/ralph_lauren_rot.png')],
    category: 'eau-de-parfum',
    type: 'original',
    gender: 'feminine',
    notes: [
      { id: '16', name: 'Rose', type: 'heart', category: 'blumig' },
      { id: '17', name: 'Moschus', type: 'base', category: 'animalisch' },
      { id: '18', name: 'Pink Pepper', type: 'top', category: 'würzig' },
    ],
    concentration: 'Eau de Parfum',
    volume: '50ml',
    availability: 18,
    isLimited: false,
    isExclusive: false,
    isNew: false,
    isOnSale: true,
    originalPrice: 75.99,
    rating: 4.4,
    reviewCount: 187,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-08'),
  },
  {
    id: 'ralph-lauren-7',
    name: 'Ralph Lauren Classic',
    brand: 'Ralph Lauren',
    description: 'Der klassische Ralph Lauren Duft für den modernen Gentleman',
    shortDescription: 'Klassischer Ralph Lauren Duft',
    price: 72.99,
    currency: 'EUR',
    images: [require('../../assets/ralph_lauren.png')],
    category: 'eau-de-parfum',
    type: 'original',
    gender: 'masculine',
    notes: [
      { id: '19', name: 'Lavendel', type: 'top', category: 'kräuter' },
      { id: '20', name: 'Holz', type: 'base', category: 'holz' },
      { id: '21', name: 'Bergamotte', type: 'top', category: 'zitrus' },
    ],
    concentration: 'Eau de Parfum',
    volume: '100ml',
    availability: 25,
    isLimited: false,
    isExclusive: false,
    isNew: false,
    isOnSale: false,
    rating: 4.3,
    reviewCount: 312,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-12'),
  },
  // Decant-Varianten der Testprodukte
  {
    id: 'hermes-parfum-decant-8',
    name: 'Hermès Parfum Decant',
    brand: 'Hermès',
    description: 'Ein exklusives Hermès Parfum als handverlesener Decant',
    shortDescription: 'Hermès Parfum Decant',
    price: 24.99,
    currency: 'EUR',
    images: [require('../../assets/hermes_parfum.png')],
    category: 'parfum',
    type: 'decant',
    gender: 'unisex',
    notes: [
      { id: '1', name: 'Rose', type: 'heart', category: 'blumig' },
      { id: '2', name: 'Sandelholz', type: 'base', category: 'holz' },
      { id: '3', name: 'Bergamotte', type: 'top', category: 'zitrus' },
    ],
    concentration: 'Parfum',
    volume: '10ml',
    availability: 3,
    isLimited: true,
    isExclusive: true,
    isNew: true,
    isOnSale: false,
    rating: 4.9,
    reviewCount: 12,
    decantInfo: {
      originalBottle: 'Hermès Parfum 50ml',
      decantDate: new Date('2024-01-20'),
      batchNumber: 'AO-2024-HERM-001',
      authenticity: true,
    },
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 'louis-vuitton-red-decant-9',
    name: 'Louis Vuitton Red Decant',
    brand: 'Louis Vuitton',
    description: 'Ein leidenschaftlicher Louis Vuitton Duft als Decant',
    shortDescription: 'Louis Vuitton Red Decant',
    price: 32.99,
    currency: 'EUR',
    images: [require('../../assets/loui_vuitton_red.png')],
    category: 'eau-de-parfum',
    type: 'decant',
    gender: 'feminine',
    notes: [
      { id: '7', name: 'Rose', type: 'heart', category: 'blumig' },
      { id: '8', name: 'Vanille', type: 'base', category: 'gourmand' },
      { id: '9', name: 'Pfeffer', type: 'top', category: 'würzig' },
    ],
    concentration: 'Eau de Parfum',
    volume: '10ml',
    availability: 2,
    isLimited: true,
    isExclusive: true,
    isNew: false,
    isOnSale: false,
    rating: 4.8,
    reviewCount: 8,
    decantInfo: {
      originalBottle: 'Louis Vuitton Red 100ml',
      decantDate: new Date('2024-01-18'),
      batchNumber: 'AO-2024-LV-001',
      authenticity: true,
    },
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: 'prada-ocean-decant-10',
    name: 'Prada Ocean Decant',
    brand: 'Prada',
    description: 'Ein erfrischender Prada Ozean-Duft als Decant',
    shortDescription: 'Prada Ocean Decant',
    price: 18.99,
    currency: 'EUR',
    images: [require('../../assets/prada_ocean.png')],
    category: 'eau-de-toilette',
    type: 'decant',
    gender: 'unisex',
    notes: [
      { id: '13', name: 'Meersalz', type: 'top', category: 'maritim' },
      { id: '14', name: 'Algen', type: 'heart', category: 'maritim' },
      { id: '15', name: 'Amber', type: 'base', category: 'orientalisch' },
    ],
    concentration: 'Eau de Toilette',
    volume: '10ml',
    availability: 7,
    isLimited: false,
    isExclusive: false,
    isNew: true,
    isOnSale: false,
    rating: 4.6,
    reviewCount: 15,
    decantInfo: {
      originalBottle: 'Prada Ocean 75ml',
      decantDate: new Date('2024-01-22'),
      batchNumber: 'AO-2024-PRADA-001',
      authenticity: true,
    },
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
]; 